### ISSUE TITLE
Instalation issue 1.3.2

### ISSUE THREAD

**Issue by rdelgado7** [sorare/crypto#16]
I can't install this version:
I have a project with a previous version works fine. but I start this and I can't install it.
Ubuntu 22.10
I tried with node 18.13.0 and 19.4.0 with nvm
can you help me?
Thanks a lot!

```username@username:~/reponame$ npm install --save @sorare/crypto@1.3.2
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated multicodec@1.0.4: This module has been superseded by the multiformats module
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated multibase@0.6.1: This module has been superseded by the multiformats module
npm WARN deprecated multibase@0.7.0: This module has been superseded by the multiformats module
npm WARN deprecated multicodec@0.5.7: This module has been superseded by the multiformats module
npm WARN deprecated cids@0.7.5: This module has been superseded by the multiformats module
npm ERR! code 1
npm ERR! path /home/username/reponame/node_modules/ffi-napi
npm ERR! command failed
npm ERR! command sh -c -- node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@18.13.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.7 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/username/reponame/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/username/reponame/node_modules/ffi-napi/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/username/reponame/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/username/.cache/node-gyp/18.13.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/username/.cache/node-gyp/18.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/username/reponame/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/username/.cache/node-gyp/18.13.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/username/reponame/node_modules/ffi-napi',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/home/username/reponame/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /home/username/reponame/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/home/username/reponame/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /home/username/reponame/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/home/username/reponame/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /home/username/reponame/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /home/username/reponame/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/username/reponame/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp ERR! System Linux 5.19.0-29-generic
npm ERR! gyp ERR! command "/home/username/.nvm/versions/node/v18.13.0/bin/node" "/home/username/reponame/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/username/reponame/node_modules/ffi-napi
npm ERR! gyp ERR! node -v v18.13.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2023-01-21T10_01_33_078Z-debug-0.log
```

**Comment by utay** [comment]
Hi @rdelgado7,

It looks like you don't have `make` installed on your machine:
```
npm ERR! gyp ERR! stack Error: not found: make
```

On Ubuntu you can run the following to install it as well as other build tools: 
```
$ sudo apt install build-essential
```

Hope this helps! Feel free to re-open if you still have an issue.
