### ISSUE TITLE
[BUG] Can't install and/or use package with local/external command "npm install" 

### ISSUE THREAD

**Issue by netzulo** [sorare/crypto#6]
# Behaviour expected

**Can install** and/or use package with local/external command "npm install"  ( https://github.com/sorare/crypto )

# Steps to reproduce behaviour

1.First test, "fresh install": FAILED

- create an empty directory ``mkdir test01``
- initialize with **npm** ``npm init --yes``
- follow README

2. Second test, "git clone+npm install": FAILED

- clone repository ``git clone https://github.com/sorare/crypto``
- enter inside repository ``cd crypto``
- install with npm ``npm install``

3. Third test, "my env should be the problem": FAILED

- clone repository ``git clone https://github.com/sorare/crypto``
- enter inside repository ``cd crypto``
- install requirements for each try of install ( ``make`` ``gcc`` )
- install with npm ``npm install``

# behaviour obtained

**Can't install** and/or use package with local/external command "npm install"  ( https://github.com/sorare/crypto )

# Documentation / Logs / Outputs / Notes

* Command **uname -a** 
```
[ubuntu@-]/etc/netzulo/test/crypto: uname -a
Linux ns516071 5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* Versions
```
[ubuntu@-]/etc/netzulo/test/crypto: npm --version
8.15.0
[ubuntu@-]/etc/netzulo/test/crypto: python3 --version
Python 3.8.10
[ubuntu@-]/etc/netzulo/test/crypto: node --version
v16.17.1
```

* Logs for **1st test**
```
[ubuntu@-]/etc/netzulo/test: npm i --save @sorare/crypto
npm ERR! code 1
npm ERR! path /etc/netzulo/test/node_modules/@sorare/crypto
npm ERR! command failed
npm ERR! command sh /tmp/install-4179fea2.sh
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.1/node-v16.17.1-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.17.1/node-v16.17.1-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.1/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.17.1/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/etc/netzulo/test/node_modules/@sorare/crypto/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ubuntu/.cache/node-gyp/16.17.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.cache/node-gyp/16.17.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/ubuntu/.cache/node-gyp/16.17.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/etc/netzulo/test/node_modules/@sorare/crypto',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.4.0-126-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /etc/netzulo/test/node_modules/@sorare/crypto
npm ERR! gyp ERR! node -v v16.17.1
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2022-10-19T02_08_48_612Z-debug-0.log
```

* Logs for **2nd test**
```
[ubuntu@-]/etc/netzulo/test/crypto: npm install
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm ERR! code 1
npm ERR! path /etc/netzulo/test/crypto/node_modules/ffi-napi
npm ERR! command failed
npm ERR! command sh /tmp/install-3193445e.sh
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/etc/netzulo/test/crypto/node_modules/ffi-napi/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ubuntu/.cache/node-gyp/16.17.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.cache/node-gyp/16.17.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/ubuntu/.cache/node-gyp/16.17.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/etc/netzulo/test/crypto/node_modules/ffi-napi',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.4.0-126-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /etc/netzulo/test/crypto/node_modules/ffi-napi
npm ERR! gyp ERR! node -v v16.17.1
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2022-10-19T02_23_26_632Z-debug-0.log
```

* Logs for **3th test**
```
[ubuntu@-]/etc/netzulo/test/crypto: npm install
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.                                                                                                                      [25/343]
npm ERR! code 1
npm ERR! path /etc/netzulo/test/crypto/node_modules/ffi-napi
npm ERR! command failed
npm ERR! command sh /tmp/install-26e0325c.sh
npm ERR! make: Entering directory '/etc/netzulo/test/crypto/node_modules/ffi-napi/build'
npm ERR!   CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
npm ERR!   AR(target) Release/obj.target/../node-addon-api/src/nothing.a
npm ERR!   COPY Release/nothing.a
npm ERR!   CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
npm ERR!   CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
npm ERR!   CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
npm ERR!   CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
npm ERR!   CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
npm ERR!   CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
npm ERR!   CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
npm ERR!   CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
npm ERR!   CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
npm ERR!   AR(target) Release/obj.target/deps/libffi/libffi.a
npm ERR!   COPY Release/libffi.a
npm ERR!   CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
npm ERR! make: Leaving directory '/etc/netzulo/test/crypto/node_modules/ffi-napi/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/etc/netzulo/test/crypto/node_modules/ffi-napi/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ubuntu/.cache/node-gyp/16.17.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.cache/node-gyp/16.17.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/ubuntu/.cache/node-gyp/16.17.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/etc/netzulo/test/crypto/node_modules/ffi-napi',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../deps/libffi/src/closures.c: In function ‘dlmmap_locked’:
npm ERR! ../deps/libffi/src/closures.c:421:7: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
npm ERR!   421 |       ftruncate (execfd, offset);
npm ERR!       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! ../deps/libffi/src/closures.c:433:7: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
npm ERR!   433 |       ftruncate (execfd, offset);
npm ERR!       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! ../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
npm ERR! ../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
npm ERR!   181 |    FFI_ASSERT (0);
npm ERR!       |                  ^
npm ERR! ../deps/libffi/src/x86/ffi64.c:156:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR!   156 |       {
npm ERR!       |       ^
npm ERR! ../deps/libffi/src/x86/ffi64.c:183:5: note: here
npm ERR!   183 |     case FFI_TYPE_FLOAT:
npm ERR!       |     ^~~~
npm ERR! make: g++: Command not found
npm ERR! make: *** [ffi_bindings.target.mk:126: Release/obj.target/ffi_bindings/src/ffi.o] Error 127
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.4.0-126-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /etc/netzulo/test/crypto/node_modules/ffi-napi
npm ERR! gyp ERR! node -v v16.17.1
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2022-10-19T02_32_53_624Z-debug-0.log

```

**Comment by utay** [comment]
Hi @netzulo, thanks for providing the logs, very helpful to debug!

There are 2 errors and it looks like you miss `make` and `g++` in order to build the C++ bindings:
- npm ERR! gyp ERR! stack Error: not found: make
- npm ERR! make: g++: Command not found

I can see in your prompt that you're using Ubuntu and you should be able to run `sudo apt-get install build-essential` to install them.

**Comment by netzulo** [comment]
Maybe fresh install of ``gcc`` and ``make`` , i can check if you think is it's help  @utay 

```
[ubuntu@-]/etc/netzulo/test/crypto: history 15 | grep apt-get
 2002  sudo apt-get install build-essential
```

```
[ubuntu@-]/etc/netzulo/test/crypto: npm i
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.

> @sorare/crypto@1.2.1 install
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.17.1 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/etc/netzulo/test/crypto/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.cache/node-gyp/16.17.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.cache/node-gyp/16.17.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ubuntu/.cache/node-gyp/16.17.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/etc/netzulo/test/crypto',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/etc/netzulo/test/crypto/build'
make: *** No rule to make target 'Release/obj.target/libcrypto/deps/crypto-cpp/src/starkware/crypto/pedersen_hash.o', needed by 'Release/obj.target/crypto.so'.  Stop.
make: Leaving directory '/etc/netzulo/test/crypto/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.4.0-126-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /etc/netzulo/test/crypto
gyp ERR! node -v v16.17.1
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok
npm ERR! code 1
npm ERR! path /etc/netzulo/test/crypto
npm ERR! command failed
npm ERR! command sh /tmp/install-7faad433.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2022-10-19T07_31_09_635Z-debug-0.log
```

**Comment by utay** [comment]
@netzulo Cool, now the error seems like the `deps/crypto-cpp` directory doesn't exist; and this directory is a git submodule. You should be able to run `git submodule update --init --recursive --remote` and then `npm i` again.

**Comment by netzulo** [comment]
> @netzulo Cool, now the error seems like the `deps/crypto-cpp` directory doesn't exist; and this directory is a git submodule. You should be able to run `git submodule update --init --recursive --remote` and then `npm i` again.

sorry but im just reporting and helping to get npm install working, not git clone + npm start, that's part of "library testing cicle".
Generally an user don't care about submodules or GCC installation problem, if don't works at first try, will not use it

* Can you @utay test by yourselft internally with a **right knowlegde and/or environment and fix us `npm install` please** ?
* When we will got a fix for ``npm i @sorare/crypto`` command from NPM ?

_ANYWAY, im letting again logs, the right "dep name" was **``ethereum-cryptography``**, not **``crypto-cpp``**_

```
[ubuntu@-]/etc/netzulo/test/crypto/node_modules/ethereum-cryptography: git submodule update --init --recursive --remote
Submodule 'deps/crypto-cpp' (https://github.com/sorare/crypto-cpp) registered for path '../../deps/crypto-cpp'
Cloning into '/etc/netzulo/test/crypto/deps/crypto-cpp'...
Submodule path '../../deps/crypto-cpp': checked out '658055e24e7803498f50c97de90ab6dccb1740a1'
```

```
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/etc/netzulo/test/crypto/build'
  CXX(target) Release/obj.target/libcrypto/deps/crypto-cpp/src/starkware/crypto/pedersen_hash.o
  CXX(target) Release/obj.target/libcrypto/deps/crypto-cpp/src/starkware/crypto/ffi/pedersen_hash.o
  CXX(target) Release/obj.target/libcrypto/deps/crypto-cpp/src/starkware/crypto/ffi/utils.o
  CXX(target) Release/obj.target/libcrypto/deps/crypto-cpp/src/starkware/crypto/ffi/ecdsa.o
  CXX(target) Release/obj.target/libcrypto/deps/crypto-cpp/src/starkware/crypto/ecdsa.o
  CXX(target) Release/obj.target/libcrypto/deps/crypto-cpp/src/starkware/crypto/elliptic_curve_constants.o
  CXX(target) Release/obj.target/libcrypto/deps/crypto-cpp/src/starkware/starkex/order.o
  CXX(target) Release/obj.target/libcrypto/deps/crypto-cpp/src/starkware/algebra/prime_field_element.o
  SOLINK(target) Release/obj.target/crypto.so
  COPY Release/crypto.so
make: Leaving directory '/etc/netzulo/test/crypto/build'
gyp info ok

> @sorare/crypto@1.2.1 postinstall
> patch-package

patch-package 6.4.7
Applying patches...
secp256k1@4.0.2 ✔

> @sorare/crypto@1.2.1 prepublish
> yarn run build

yarn run v1.22.0
warning ../package.json: "test" is also the name of a node core module
$ yarn run build:types && yarn run build:js
warning ../package.json: "test" is also the name of a node core module
$ tsc --emitDeclarationOnly
warning ../package.json: "test" is also the name of a node core module
$ babel src --out-dir dist --extensions ".js,.ts" --source-maps inline
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Successfully compiled 7 files with Babel (578ms).
Done in 5.10s.
```

**Comment by utay** [comment]
@netzulo Thanks for the feedback. Indeed this library compiles C++ code, hence it needs some prerequisites like make and g++ and the code comes from a [git submodule](https://github.com/sorare/crypto-cpp/tree/658055e24e7803498f50c97de90ab6dccb1740a1) that needs to be pulled. We can add that to the [README](https://github.com/sorare/crypto#c-bindings) for development purposes. However, most users generally don't need to care about this and add [@sorare/crypto](https://www.npmjs.com/package/@sorare/crypto) to their package.json deps which doesn't require them to pull submodules, etc

**Comment by utay** [comment]
> When we will got a fix for npm i @sorare/crypto command from NPM ?

Sorry, forgot to answer this. There are no pre-built binaries available for now for this library so every time someone installs it, they have to compile the C++ bindings. This is something we thought about and will surely add in the future

**Comment by netzulo** [comment]
> most users generally don't need to care about this an

ty, i think is ok with update over DEVELOPMENT process 

if it's ok i want to recommend one "temporal change" like this to help on this kind of setups 🙏 

```diff
  "scripts": {
    "clean": "rm -rf dist/",
    "lint": "yarn run eslint src/*.ts --max-warnings 0",
    "build": "yarn run build:types && yarn run build:js",
    "build:types": "tsc --emitDeclarationOnly",
    "build:js": "babel src --out-dir dist --extensions \".js,.ts\" --source-maps inline",
    "prepublish": "yarn run build",
    "postinstall": "patch-package",
    "test": "jest ./src",
    "package": "yarn build && rm dist/index.test.* && yarn pack",
    "release": "yarn clean && yarn version && yarn package && npm publish *.tgz --access public"
+   "install:development": "cd deps/crypto-cpp && git submodule update --init --recursive --remote && npm install"
  },
```
